# Generated by Django 4.2.5 on 2023-09-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='routine',
        ),
        migrations.AddField(
            model_name='routine',
            name='exercise',
            field=models.ManyToManyField(blank=True, through='routines.Routine_has_exercise', to='routines.exercise'),
        ),
        migrations.AlterField(
            model_name='routine_has_exercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.exercise'),
        ),
        migrations.AlterField(
            model_name='routine_has_exercise',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.routine'),
        ),
        migrations.CreateModel(
            name='User_has_Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.user')),
            ],
        ),
    ]
