name: Initialize Django App

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Update ubuntu
        run: sudo apt update

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install pip
        run: sudo apt install python3-pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test if Django runs the development server
        run: |
          echo "Going to  virtual_c folder"
          cd virtual_c
          echo "Executing development server"
          python manage.py runserver

    